### PR TITLE
JSHINT TO ESLINT

### PR DESCRIPTION
**Pull request by radomala**
Hello, I propose you my PR, my work for the spot of Passage to ESLint in place of JShint. Thank you

### CODE REVIEW

**Comment by juji** [comment]
mocha should provide the test it needs.. thank you anyway.. :)



:)

May the awesomeness will always be with you,

Tri Rahmat Gunadi - JUJI
http://jujiyangasli.com
Ph 0813.1012.8924

**Comment by radomala** [comment]
Hello,
I did not really understand your answer, can you tell me what should I do, or can you merge my PR (JSHINT TO ESLINT) please, so that I can advance in the contribution.
Thank you

**Comment by radomala** [comment]
Hello,
This last commit trigers the linting automatically once the mocha tests are finished. That may be what you were asking.

**Comment by madarche** [comment]
Hello @juji, any reason not to merge this PR? This PR is good 👍

**Comment by juji** [comment]
so, decided to merge the pull request... so @radomala can advance in the contribution. Remarkable what you can do to a person status by pressing a button.

**Comment by madarche** [comment]
Thank you @juji!

**Pull request merged**
